name: hello world

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display Hello World Message
        run: "Echo, hello world....."
  
      - name: Another Task
        run: "Echo, another hello world....."
